# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- foobar

pool:
  vmImage: ubuntu-latest
variables:
  MajorVersion: 1
  MinorVersion: 0
  PatchVersion: 0

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/*.csproj
      !**/*Win*.csproj
      !**/*Tool*.csproj

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*Win*.csproj;!**/*Tool*.csproj'
    configuration: 'Release'
    includesymbols: true
    includesource: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(MajorVersion)'
    minorVersion: '$(MinorVersion)'
    patchVersion: '$(PatchVersion)'
    verbosityPack: 'Minimal'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '27a99079-832f-4146-965e-ee990d627466/ba90ae64-33d1-43dd-9599-e83d01fbad94'